version: '3.7'

services:
  openldap:
      image: osixia/openldap:1.5.0
      container_name: openldap
      domainname: "company.com"
      hostname: "ldap-server"
      environment:
        LDAP_ORGANISATION: "My Company"
        LDAP_DOMAIN: "company.com"
        LDAP_ADMIN_PASSWORD: "passw0rd"
        LDAP_CONFIG_PASSWORD: "passw0rd"
        LDAP_TLS: "true"
        LDAP_TLS_CRT_FILENAME: "ldap.crt"
        LDAP_TLS_KEY_FILENAME: "ldap.key"
        LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
        LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
        LDAP_TLS_ENFORCE: "false"
        LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
        LDAP_TLS_VERIFY_CLIENT: "demand"
      volumes:
        - /var/lib/ldap
        - /etc/ldap/slapd.d
        - /container/service/slapd/assets/certs/
      ports:
        - 389:389
        - 636:636
      restart: always      

  phpLDAPadmin:
        image: osixia/phpldapadmin:0.9.0
        container_name: phpLDAPadmin
        environment:
          PHPLDAPADMIN_LDAP_HOSTS: "openldap"
          PHPLDAPADMIN_HTTPS: "true"
          PHPLDAPADMIN_HTTPS_CRT_FILENAME: "my-cert.crt"
          PHPLDAPADMIN_HTTPS_KEY_FILENAME: "my-cert.key"
          PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: "the-ca.crt" 
        volumes:
          - /path/to/certifates:/container/service/phpldapadmin/assets/apache2/certs
        ports:
          # - 8080:80
          - 6443:443
        restart: always
        depends_on:
          - openldap